version: '3.4'

services:
  oneauthservice:
    image: oneauthservice:latest
    container_name: oneauthservice
    restart: always
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8005:8005
    environment:
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_URL: https://app.oneauth.ioak.io
    networks:
      ioak-net:
        aliases:
          - oneauthservice.docker

networks:
  ioak-net:
      name: ioak-network
