version: '3.4'

services:
  # mongo:
  #   image: mongo:4.2.3-bionic
  #   container_name: mongo
  #   restart: always
  #   volumes: 
  #     - /mnt/disks/sdb/data/db:/data/db
  #   ports:
  #       - 27017:27017
  #   networks:
  #     ioak-net:
  #       aliases:
  #         - mongo.docker

  oneauthservice:
    image: oneauthservice:latest
    container_name: oneauthservice
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      MONGODB_URI: mongodb://mongo.docker:27017
    networks:
      ioak-net:
        aliases:
          - oneauthservice.docker

networks:
  ioak-net:
      name: ioak-network
