version: '3.4'

services:
  oneauthservice:
    image: oneauthservice:latest
    container_name: oneauthservice
    # depends_on:
    #   - mongo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8010:8010
    environment:
      MONGODB_URI: mongodb://mongo.docker:27017
    networks:
      ioak-net:
        aliases:
          - oneauthservice.docker

networks:
  ioak-net:
      name: ioak-network
